version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fresh-bot-v1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m5xu4jhlhuhz"
s3_prefix = "fresh-bot-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

